GOOGLE_DORKS = [
    'site:{target} inurl:admin',
    'site:{target} intitle:index.of',
    'site:{target} filetype:pdf',
    'site:{target} intext:password',
    'site:{target} ext:php',
    'site:{target} ext:sql',
    'site:{target} ext:log',
    'site:{target} ext:conf',
    'site:{target} ext:bak',
    'site:{target} ext:old',
    'site:{target} ext:txt',
    'site:{target} ext:env',
    'site:{target} ext:yml',
    'site:{target} ext:ini',
    'site:{target} ext:cfg',
    'site:{target} ext:xml',
    'site:{target} ext:json',
    'site:{target} ext:csv',
    'site:{target} "BEGIN OPENSSH PRIVATE KEY"',
    'site:{target} ext:nix "BEGIN OPENSSH PRIVATE KEY"',
    'site:{target} intext:"aws_access_key_id" | intext:"aws_secret_access_key" filetype:json | filetype:yaml',
    'site:{target} intitle:index of /etc/ssh',
    'site:{target} intitle:"Index of" pwd.db',
    'site:{target} intitle:"Index of" htpasswd',
    'site:{target} intext:"password"',
    'site:{target} intext:"index of" "uploads"',
    'site:{target} intext:"/pfx-password.txt" "[To Parent Directory]"',
    'site:{target} inurl:/wp-content/uploads/ ext:txt "username" | "user name" | "uname" | "user" | "userid" | "user id" AND "password" | "pass word" | "pwd" | "pw"',
    'site:{target} inurl:password site:shodan.io',
    'site:{target} intitle:"index of" "password*"',
    'site:{target} intitle:"index of" "credentials"',
    'site:{target} allintext:password filetype:log after:2018',
    'site:{target} inurl:wp-config.php.save',
    'site:{target} "enable secret 5" ext:txt | ext:cfg',
    'site:{target} inurl:/wp-content/uploads/ ext:txt "username" AND "password" | "pwd" | "pw"',
    'site:{target} intitle:"index of" "anaconda-ks.cfg" | "anaconda-ks-new.cfg"',
    'site:{target} "anaconda-ks.cfg" | "ks.cfg" ext:cfg -git -gitlab',
    'site:{target} "index of" "password.ini"',
    'site:{target} intitle:"database.php" inurl:"database.php" intext:"db_password" -git -gitlab',
    'site:{target} "/** MySQL database password */" ext:txt | ext:cfg | ext:env | ext:ini',
    'site:{target} "EMAIL_HOST_PASSWORD" ext:yml | ext:env | ext:txt | ext:log',
    'site:{target} allintext:"redis_password" ext:env',
    'site:{target} intext:"db_database" ext:env intext:"db_password"',
    'site:{target} "Index of" "/yahoo_site_admin/credentials"',
    'site:{target} intitle:"index of" "/master.passwd"',
    'site:{target} "MYSQL_ROOT_PASSWORD:" ext:env OR ext:yml -git',
    'site:{target} "index of" ".env"',
    'site:{target} filetype:env "DB_PASSWORD"',
    'site:{target} "MYSQL_ROOT_PASSWORD:" ext:env OR ext:yml -git',
    'site:{target} "config.php.bak" intitle:"index of"',
    'site:{target} intitle:"index of" "config.neon" OR "config.local.neon"',
    'site:{target} inurl:*helpdesk* intext:"your default password is"',
    'site:{target} "/etc/shadow root:$" ext:cfg OR ext:log OR ext:txt OR ext:sql -git',
    'site:{target} filetype:xml config.xml passwordHash Jenkins',
    'site:{target} intext:jdbc:oracle filetype:java',
    'site:{target} filetype:txt $9$ JunOS',
    'site:{target} filetype:reg reg HKEY_CURRENT_USER intext:password',
    'site:{target} inurl:"standalone.xml" intext:"password>"',
    'site:{target} /_wpeprivate/config.json',
    'site:{target} inurl:"build.xml" intext:"tomcat.manager.password"',
    'site:{target} intitle:"index of" intext:login.csv',
    'site:{target} inurl:"wp-license.php?file=../..//wp-config"',
    'site:{target} inurl:wp-config.bak',
    'site:{target} "whoops! there was an error." "db_password"',
    'site:{target} intext:"rabbit_password" | "service_password" filetype:conf',
    'site:{target} intext:"login" department | admin | manager | company | host filetype:xls | xlsx -community -github',
    'site:{target} intext:"please change your" password |code | login file:pdf | doc | txt | docx -github',
    'site:{target} inurl:configuration.php and intext:"var $password="',
    'site:{target} filetype:env intext:REDIS_PASSWORD',
    'site:{target} "password.xlsx" ext:xlsx',
    'site:{target} inurl:"-wp13.txt"',
    'site:{target} filetype:inc OR filetype:bak OR filetype:old mysql_connect OR mysql_pconnect',
    'site:{target} allinurl:"User_info/auth_user_file.txt"',
    'site:{target} inurl:"/dbman/default.pass"',
    'site:{target} inurl:"/Application Data/Filezilla/*" OR inurl:"/AppData/Filezilla/*" filetype:xml',
    'site:{target} filetype:sql "PostgreSQL database dump" (pass|password|passwd|pwd)',
    'site:{target} filetype:sql "MySQL dump" (pass|password|passwd|pwd)',
    'site:{target} filetype:sql "phpmyAdmin SQL Dump" (pass|password|passwd|pwd)',
    'site:{target} intitle:"Index of" .mysql_history',
    'site:{target} intitle:"Index of" ".htpasswd" "htgroup" -intitle:"dist" -apache -htpasswd.c',
    'site:{target} intitle:"Index of" spwd.db passwd -pam.conf',
    'site:{target} intitle:index.of people.lst',
    'site:{target} intitle:index.of config.php',
    'site:{target} intitle:index.of trillian.ini',
    'site:{target} intitle:"index of" intext:globals.inc',
    'site:{target} intitle:"index of"',
    'site:{target} intitle: index of /concrete/Password',
    'site:{target} intitle:"index of" database.properties',
    'site:{target} intitle:Index of "/venv"',
    'site:{target} intitle:Index of "pyvenv.cfg"',
    'site:{target} intitle:index of ..................etcpasswd',
    'site:{target} intitle:"index of /" "sqlite.db"',
    'site:{target} intitle:"index of" ".env"',
    'site:{target} intitle:" index of "/Invoices*"',
    'site:{target} intitle: "index of backup.xml"',
    'site:{target} intitle: "index of backup.php"',
    'site:{target} intitle:"index of SCADA"',
    'site:{target} intitle:"index of" "private/log"',
    'site:{target} intitle: "Index of" inurl:fileadmin',
    'site:{target} intitle:"index of" "contacts.vcf"',
    'site:{target} intitle:"index of" "/configs"',
    'site:{target} inurl:filemanager/upload/asp/ "index of"',
    'site:{target} intext:"CAD Media Log"',
    'site:{target} intitle:"index of" "/.vscode"',
    'site:{target} intitle:"index of" "/__pycache__"',
    'site:{target} inurl:wp-content/uploads/ intitle:logs',
    'site:{target} inurl:/wp-content/uploads/wp-file-manager-pro/fm_backup',
    'site:{target} "-----BEGIN EC PRIVATE KEY-----" | " -----BEGIN EC PARAMETERS-----" ext:pem | ext:key | ext:txt',
    'site:{target} "-----BEGIN PGP PRIVATE KEY BLOCK-----" ext:pem | ext:key | ext:txt -git',
    'site:{target} inurl:tcpconfig.html',
    'site:{target} inurl:print.htm intext:"Domain Name:" + "Open printable report"',
    'site:{target} inurl:/certs/server.key',
    'site:{target} inurl:/jsps/testoperation.jsp "Test Operation"',
    'site:{target} intitle:"index of" "*Maildir/new"',
    'site:{target} intitle:("Index of" AND "wp-content/plugins/boldgrid-backup/=")',
    'site:{target} "-- Dumped from database version" + "-- Dumped by pg_dump version" ext:txt | ext:sql | ext:env | ext:log',
    'site:{target} /etc/config + "index of /" /',
    'site:{target} /etc/certs + "index of /" */*',
    'site:{target} intitle:"index of" "dump.sql"',
    'site:{target} "-- Dumping data for table `admin`" | "-- INSERT INTO `admin`" "VALUES" ext:sql | ext:txt | ext:log | ext:env',
    'site:{target} intitle: "Index of" inurl:admin/uploads',
    'site:{target} inurl:node_modules/mqtt/test/helpers/',
    'site:{target} "index of" "mysql.sh"',
    'site:{target} intitle:"index of" "/system.log" | "/system.logs"',
    'site:{target} intitle:"index of" "slapd.conf"',
    'site:{target} "-- Dumping data for table * " ext:sql | ext:xls intext:db | intext:database | intext:password | username',
    'site:{target} intitle:"index of" "/app.log" | "/app.logs"',
    'site:{target} "index of" "performance_schema"',
    'site:{target} ext:reg [HKEY_CURRENT_USERSoftwareSimonTathamPuTTYSshHostKeys]',
    'site:{target} intitle:"index of" "/000~ROOT~000/"',
    'site:{target} intitle:"index of" "firewall.log" | "firewall.logs"',
    'site:{target} intitle:"Index of /" +.htaccess.old',
    'site:{target} Index: /wp-includes/Text/Diff',
    'site:{target} inurl:/~bangpeng/download/texting_message/texting_message_all.txt',
    'site:{target} intitle:"Index of /guidelines/php/cmd"',
    'site:{target} intitle:"Index of c:xampp"',
    'site:{target} intitle:"index of" "/root/etc/security/"',
    'site:{target} intitle:"index of" "survey.cgi"',
    'site:{target} intitle:"index of" "symfony/config"',
    'site:{target} "index of" "/config/sql"',
    'site:{target} intitle:"index of" "admin/config"',
    'site:{target} intitle:"index of" "git-jira-log"',
    'site:{target} intitle:"index of" "owncloud/config/*"',
    'site:{target} intitle:"index of" "cctv"',
    'site:{target} /_wpeprivate/config.json',
    'site:{target} inurl:"/wp-content/uploads/db-backup"',
    'site:{target} intitle:index of /.sql.gz intext:/backup/',
    'site:{target} intitle:"index of /" authorized_keys',
    'site:{target} intitle:"index of" "access_log"',
    'site:{target} "index of" "database_log"',
    'site:{target} intitle:index.of home/000~root~000/',
    'site:{target} inurl:/openwebmail/cgi-bin/openwebmail/etc/',
    'site:{target} intext:/wp-content/plugins/woocommerce/templates/emails/plain/',
    'site:{target} intext:"Index of /database"',
    'site:{target} intext:"Index of /.git"',
    'site:{target} intitle:"Index of" "wwwroot"',
    'site:{target} inurl:/cgi-bin/.cgi',
    'site:{target} inurl:ckfinder intext:"ckfinder.html" intitle:"Index of /ckfinder"',
    'site:{target} intitle:"Index of c:\Windows"',
    'site:{target} intitle:"Index of /download/"',
    'site:{target} intitle:index.of.config',
    'site:{target} intitle:index.of intext:.bash_history',
    'site:{target} intitle:"Index of /finance"',
    'site:{target} intitle:"Index of /wp-includes"',
    'site:{target} intitle:"Index of ftp"',
    'site:{target} "index of" inurl:root intitle:symlink',
    'site:{target} inurl:"images/lists?cid=13"',
    'site:{target} inurl:nagios/cgi-bin/status.cgi',
    'site:{target} "ansible.log" | "playbook.yaml" | ".ansible.cfg" | "playbook.yml" | host.ini intitle:"index of"',
    'site:{target} inurl:/adm-cfgedit.php',
    'site:{target} inurl:phpSysInfo/ "created by phpsysinfo"',
    'site:{target} inurl:server-status "apache"',
    'site:{target} inurl:"server-status" intext:"Apache Server Status"',
    'site:{target} intitle:"Apache::Status" (inurl:server-status | inurl:status.html | inurl:apache.html)',
    'site:{target} intitle:"Welcome to WildFly" intext:"Administration Console"',
    'site:{target} intitle:"Index of" site:.gov intext:"Server at"',
    'site:{target} intitle:"Welcome" intext:"LiteSpeed Technologies, Inc. All Rights Reserved."',
    'site:{target} intitle:"index of" "/homedir/etc/"',
    'site:{target} "Cisco Systems, Inc. All Rights Reserved." -cisco.com filetype:jsp',
    'site:{target} inurl:"/phpmyadmin/user_password.php',
    'site:{target} inurl:/iisstart.htm intitle:"IIS7"',
    'site:{target} intitle:"Index of" "Apache/2.4.7 (Ubuntu) Server"',
    'site:{target} inurl:/_catalogs',
    'site:{target} inurl:/php/info.php',
    'site:{target} "PHP Credits" "Configuration" "PHP Core" ext:php inurl:info',
    'site:{target} inurl:"/web-console/" intitle:"Administration Console"',
    'site:{target} intext:Apache/2.2.29 (Unix) mod_ssl/2.2.29 | intitle:"Index of /"',
    'site:{target} intitle:"Test Page for Apache" "It Worked!" "on this web"',
    'site:{target} allintext:wp-includes/rest-api',
    'site:{target} intitle:"index of" "*.phtml"',
    'site:{target} intitle:"index of" "*.pl"',
    'site:{target} intitle:"index of" "*.php"',
    'site:{target} intitle: Index of /assets/admin/system',
    'site:{target} intitle:"index of" "schema.sql"',
    'site:{target} "index of /" intext:wp-config "zip"',
    'site:{target} index of admin/fckeditor/editor/filemanager/',
    'site:{target} inurl:install.php intitle:"Froxlor Server Management Panel - Installation"',
    'site:{target} inurl:/+CSCOE+/logon.html',
    'site:{target} intitle:"index of" "AT-admin.cgi"',
    'site:{target} ext:cgi inurl:cgi-bin intext:#!/bin/bash',
    'site:{target} inurl:"/reports/rwservlet" intext:"Oracle"',
    'site:{target} intitle:phpMyAdmin "Welcome to phpMyAdmin ***" "running on * as root@',
    'site:{target} inurl:info.inc.php',
    'site:{target} "Welcome to PHP-Nuke" congratulations',
    'site:{target} inurl:"cgi-bin/koha"',
    'site:{target} intitle:"index of" "stacktrace.log"',
    'site:{target} intitle:"index of" "my-errors.log" OR "my-errors.logs"',
    'site:{target} intitle:"index of" errors.log',
    'site:{target} inurl:"/WebResource.axd?d=" AND intext:Error',
    'site:{target} inurl:("/storage/logs/laravel.log") AND intext:("local.ERROR" | "NULL.ERROR" | "EMERGENCY:")',
    'site:{target} inurl:".php?id=" "You have an error in your SQL syntax"',
    'site:{target} "Warning: mysql_query()" "invalid query"',
    'site:{target} "ORA-00933: SQL command not properly ended"',
    'site:{target} "ORA-00921: unexpected end of SQL command"',
    'site:{target} "ORA-00936: missing expression"',
    'site:{target} "ORA-00921: unexpected end of SQL command"',
    'site:{target} intitle:index of /etc/openldap',
    'site:{target} filetype:xls "root" database',
    'site:{target} intitle:"index of" env.cgi',
    'site:{target} inurl:* "auditing.txt"',
    'site:{target} intitle:"Index of /confidential"',
    'site:{target} intitle:index.of /logs.txt',
    'site:{target} ext:db',
    'site:{target} ext:db1',
    'site:{target} ext:db2',
    'site:{target} ext:db3',
    'site:{target} ext:db4',
    'site:{target} ext:db5',
    'site:{target} ext:db*',
    'site:{target} "index of" "./" "./bitcoin"',
    'site:{target} inurl:/wp-content/uploads/ ext:txt "username" | "user name" | "uname" | "user" | "userid" | "user id" AND "password" | "pass word" | "pwd" | "pw"',
    'site:{target} intitle:"index of" "application-users.properties" | "mgmt-users.properties" | "*standalone.xml"',
    'site:{target} ext:log password END_FILE',
    'site:{target} intitle:"index of" "/master.passwd"',
    'site:{target} intitle:"index of" "config.neon" OR "config.local.neon"',
    'site:{target} intitle:"index of" "credentials.yml"',
    'site:{target} intitle:"index of" "passwords.yml"',
    'site:{target} intext:"WPENGINE_SESSION_DB_USERNAME" || "WPENGINE_SESSION_DB_PASSWORD"',
    'site:{target} intext:"username=" AND "password=" ext:log',
    'site:{target} intitle:"index of " "shell.txt"',
    'site:{target} intitle:"index of" "config.html"',
    'site:{target} intitle: index of /concrete/Password',
    'site:{target} intitle:"index of" database.properties',
    'site:{target} intitle:Index of "/venv"',
    'site:{target} intitle:Index of "pyvenv.cfg"',
    'site:{target} intitle:"index of" "jwt-auth"',
    'site:{target} intitle:"index of" "/concrete/Authentication"',
    'site:{target} intitle:"index of" "apache-log-parser" "Port 80"',
    'site:{target} intitle:"index of" "metadata"',
    'site:{target} intext:"index of /" ".composer-auth.json"',
    'site:{target} inurl:"/includes/OAuth2" intext:"index of /"',
    'site:{target} intitle:"index of" inurl:wp-json embedurl?',
    'site:{target} inurl:concrete/config/',
    'site:{target} intitle:"index of" "sms.log"',
    'site:{target} intitle:"index of" "ftp.log"',
    'site:{target} intitle:"index of" .zshrc~ OR .zshrc OR .zshenv OR .zshenv~ -pool -public',
    'site:{target} intitle:"index of" .oracle_jre_usage/',
    'site:{target} intitle:"index of" domain.key -public',
    'site:{target} index of /storage/logs/',
    'site:{target} intitle:index.of "htaccess.txt"',
    'site:{target} index.of: /android/manifest.xml',
    'site:{target} inurl:"/proguard.cfg"',
    'site:{target} intitle:index.of "system.db"',
    'site:{target} intitle:index.of "database.db"',
    'site:{target} intitle:index.of./.htaccess',
    'site:{target} indexof:backup/mysql',
    'site:{target} indexof:.htaccess',
    'site:{target} index of /ftp/backup',
    'site:{target} intitle:"index of" /config.ini',
    'site:{target} intitle:"index of" ".cpanel/caches/config/"',
    'site:{target} intitle:"Directory Listing For" "Filename" intext:Tomcat/5.0.28',
    'site:{target} intitle:"index of /" intext:/backup',
    'site:{target} intitle:index of /.sql.gz intext:/backup/',
    'site:{target} Index of /.svn',
    'site:{target} inurl:"/cms/app/webroot"',
    'site:{target} index.of.secret',
    'site:{target} inurl:"/phpmyadmin/user_password.php',
    'site:{target} intitle:"Webcam" inurl:WebCam.htm',
    'site:{target} intitle:"Toshiba Network Camera"',
    'site:{target} inurl:7001/console intitle:weblogic',
    'site:{target} intitle:" SyncThru Web Service" intext:"Supplies Information"',
    'site:{target} inurl:/multi.html intitle:webcam',
]
